### ISSUE TITLE
Luna 1.1 "Bittersweet Shimmer" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1100]
So here we are, ready to release Luna 1.1 "Bittersweet Shimmer". This updates brings a lot of small improvements on top of our original and first Luna 1.0 release. It comes mainly with improved features that where introduced in Aero, and bug fixes.

# Features
### Profile
- [x] #1232 **Contact links**: links to Twitter, Facebook and your Microsoft account in the profile now have a clickeable button.

### User Experience
- [x] #1246 **Night mode**: a new setting for users to make Luna switch to a more eye-friendly night version of themes.
- [x] #1265  **Error enhancements**: some errors make issues out of nothing, no reason for that, so we changed the behavior of these errors to actualy help you.
- [x] #1282 **AJAX notifications**: notifications are now handled by AJAX.
- [x] #1283 **AJAX notification improvements**: multiple improvements to the AJAX implementation for notifications and the notification functionality.

## Backstage
- [x] #1245 **Backstage accent**: after this feature got removed in Aero, we'll be bringing back the abbility to change the Backstage's color in your profile.
- [x] #1261 **Default color accent**: you can now chnage the default color accent of the mainstage, in case the default doesn't match your board.
- [x] #1274 **Announcement options**: you can now give titles to announcements and change their style, for the default Fifteen and Sunrise themes, which support warning, success, info and danger.
- [x] #1295 **Site specific cookie info**: you can now change the URL that the cookie bar links to a custom URL.

## System
- [x] #1098 **SEO enhancements**: Bittersweet Shimmer will come with improvements for search engines. We'll add relevant meta data to all pages and other optimisations, like the use of canonical tags.
- [x] #1238 **Better color scheme system**: the color scheme system for styles has been updated.
- [x] #1270 #1271 **Notifications API**: there is now an API for notifications.
- [x] #1289 **Brand update**: the color scheme and logos for Luna have been updated to reflect the recent brand changes.
- [x] #1294 **HTML description**: you can now use HTML in your forum descriptions.
- [x] #1303 **PHP 7 support**: Luna now supports PHP 7-based environments.

### Translations
- [x] #1240 #1272 **Gettext translations**: translations are now based on gettext.
- [x] #1286 **Missing strings**: some strings where missing in the new translation files and have now been added.

### Themes
- [x] **Simpler Theme engine**: it will require less files to create a theme and the themes can be more unified.

# Bugfixes
- [x] #1228 The number of views no longer gets cut of when the thread title is to long.
- [x] #1267 Fixes undefined variable body_classes.
- [x] #1293 Fixes issue with unexpected T_STRING.
- [x] #1298 Fix support for PHP 5.2 with new language files.
- [x] #1301 Fixes bugs with night mode.
