### ISSUE TITLE
Luna 1.0.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1253]
Luna 1.0.1 is our first minor update to Luna. This release fixes some of the issues that didn't make it into the official release and where discovered after its availablility.

## Improvements
- [x] #1229 Luna now uses tooltips for emoticons in the editor.
- [x] #1251 Lunicons 0.0.0 has been added and replaces the fa-moon-o icon.
- [x] #1255 ```$cur_index``` is no longer hardcoded, improves focus.
- [x] 2a4a859 Remove a query from the update script that isn't used anymore.

## Bugfixes
- [x] #1244 Fixes an issue that causes external files not to load when SSL is enabled.
- [x] #1252 Update index behavior to show the most recent topics instead of the most recently updated 30 newest topics.
- [x] #1254 Fix confirm_referrer issue with double ```//```.
- [x] #1257 Disabling First Run will no longer cause a ```HTTP_REFERRER``` error.
- [x] e613b5f Fixes a design flaw in the editor interface.
- [x] 895859a Remove the beta tag from the About page in Backstage.
- [x] aab49a3 Fixes a visual glitch when the extension menu appears in the Backstage.
