### ISSUE TITLE
Luna 1.0.2 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1263]
Luna 1.0.2 is our second minor update to Luna Aero and comes with bug fixes and small improvements.

## Enhancements
- [x] #1258 When showing posts, the results will now link to the specific post instead of the topic.
- [x] #1260 When you write a new message in Inbox, the "Send to" field will now have focus by default.
- [x] #1262 When an user receives a new Inbox message, they will now get a mail (with content) to notify them about it.
- [x] #1268 The installer will no longer add o_smilies
- [x] e2dc33e The (soft) delete and reset interface has been given a small visual update.
- [x] b82b944 Visual improvements for the dropdown menu when in mobile mode.
- [x] e6e6880 Visual improvements for secondary navbars with collapsable navigation when in mobile mode.

## Bugfixes
- [x] #1259 Fixes undefined index message in Inbox.
- [x] #1266 Updating will no longer reset the theme to Luna.
