### ISSUE TITLE
Luna 1.0.3 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1276]
Luna 1.0.3 is our third minor update to Luna Aero and comes with bug fixes and small improvements.

## Enhancements
- [x] f3354ae When you're using the Slow Ring and the branch is labeled as end of life, you now get a warning that this is the case and that you should check for updates in the Normal branch.
- [x] 83eda41 Some icons have been added to the Backstage interface for more consistency.

## Bug fixes
- [x] #1273 When canceling a quote, you're now send back to the correct topic.
- [x] 7cb75af You no longer get redirected to login.php after trying to login for a second time.
- [x] fb420da A small placement bug with a button in the settings has been fixed.
