### ISSUE TITLE
Luna 1.0.7 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1311]
Luna 1.0.7 is a small update for PHP 7.0 users, for whatever reason you would be using that version of PHP right now... It also brings an updated Bootstrap version and support for SQLite 3.

## Improvements
- [x] #1312 The moderator interface in the Backstage is more polished.
- [x] #1316 When a user's post is removed, his/here post count will now decrease.

## Platform support
- [x] #1303 PHP 7 is now supported by Luna.
- [x] #1305 SQLite 3 is now supported by Luna.

## Components
- [x] #1310 Bootstrap 3.3.4 has been updated to 3.3.5.

## Bug fixes
- [x] #1319 Fix issue with verification email addresses.
