### ISSUE TITLE
Luna 1.1.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1314]
Luna 1.1.1 is our first minor update to Bittersweet Shimmer, and comes with an improved moderator interface, SQLite 3 support, updated components and more!

## Improvements
- [x] #1313 The moderator interface in the Backstage is more polished.
- [x] #1317 When a user's post is removed, his/here post count will now decrease.
- [x] #1322 You can now disable night mode and custom accents.
- [x] #1324 Some out-of-date references in the language files have been removed.

## Platform support
- [x] #1306 SQLite 3 is now supported by Luna.

## Components
- [x] #1309 Bootstrap 3.3.4 has been updated to 3.3.5.

## Bug fixes
- [x] #1320 Fix issue with verification email addresses.
- [x] #1321 Fix issue when config.php is wrong.
- [x] #1323 Fix strings for night mode not being used.
