### ISSUE TITLE
Luna 1.2 "Cornflower Blue" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1332]
Luna 1.2 is the second update to Luna and comes with small feature improvements and other changes.

### Mainstage
- [x] #1292 **Solved**: users can now mark their topic as solved.
- [x] #1331 **Syntax highlight**: the syntax highlighter now supports more languages like C, C++, C# and Pascal.

### Backstage
- [x] #1099 **Notification cleanup**: we've added new options to clean up notifications.
- [x] #1315 **Moderator interface**: the moderator interface in the Backstage is more polished.
- [x] #1337 **Color picker for forums**: instead of the limited set of colors Luna used to provide, you're now free to set any color as a forum's accent color.

### System
- [x] #220 #245 **SQLite 3 support**: SQLite 3 is now supported by Luna.
- [x] #1325 **No Javascript**: Luna is now more usable when Javascript has been disabled.
- [x] #1343 **Nonces**: Luna now has also a nonces based security feathre.
- [x] #1359 **Avatar formats**: avatars now have a default max width and height of 128 pixels and max size of 30720 bytes.
- [x] #1365 **Email validation**: the email validation syntax has been updated to disallow weird email addresses.
- [x] #1372 **Table improvements**: tables with checkboxes have been improved on multiple points, like "select all", "click anywhere" and highlighting.
- [x] #1386 **Input types**: some input types have been changed to number and date for an improved mobile experience.

## Themes
- [x] #1335 **Enforce accent**: themes can now use the new enforce_accent feature to make their themes more colorful.
- [x] #1336 **Improved themes**: Fifteen and Sunrise will get updated to version 1.2 with minor improvements and enhancements and support for new features.
- [x] #1366 **Registration form customization**: the registration form can now be customized much easier.

### Improvements
- [x] #1318 **Post decrease**: When a user's post is removed, his/here post count will now decrease.
- [x] #1341 **Language support**: Support for non-Latin characters in the Backstage.
- [x] #1368 **Terminology**: since Luna 1.0, we've taken a run with terminology. Luna 1.2 unifies this once again.
- [x] #1369 **Label icons**: in a note to the "Solved" feature, we've changed the "Moved", "Pinned" and "Closed" labels to icons.
- [x] #1370 **SEO enhancements**: we've added more SEO enhancements.
- [x] #1385 **Forum icons**: you can now select an icon from the full Font Awesome library as the icon for a forum.

### Components
- [x] #1308 **Bootstrap 3.3.5**: Bootstrap 3.3.4 has been updated to 3.3.5.
 - On this subject: we've also updated the Bootstrap version used by the installer to version 3.3.5 (up from 3.2.0) and both Fifteen and Sunrise are now also using version 3.3.5 (up from 3.3.4). Luna was updated to 3.3.5 in Luna 1.1.1, but these 3 parts did not get affected by the update.
- [x] #1329 **Build-in compontents**: Bootstrap, Font Awesome and jQuery are now build-in.
- [x] #1350 **Font Awesome 4.4.0**: Font Awesome 4.3.0 has been updated to 4.4.0.
- [x] #1361 **Glyphicons in Bootstrap**: the corporated style no longer has the Glyphicons build in, as this is already something we've got Font Awesome for. FA is still in active development, while Glyphicons are deprecated by Bootstrap.

## Bug fixes
- [x] #788 Fix wrong directory for common.js file in user page.
- [x] #1340 Fix a small spelling mistake.
- [x] #1342 A potential issue on mobile devices has been fixed where an user was unable to post.
- [x] #1364 The Backstage will now look in the current theme's parrent folder for accents instead of the child.
- [x] #1378 Luna doesn't allow certain correct mail addresses.
- [x] #1389 Fixes a fatal error mysqli_free_result.
- [x] #1391 Exclude newlines when parsing username in quote tag.
- [x] #1407 Fix for PostgreSQL drivers.
- [x] #1408 Fix corrupted lang.po for English.
