### ISSUE TITLE
Luna 1.0.8 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1347]
Luna 1.0.8 is the final update to Luna 1.0.

## Improvements
- [x] #1345 The Slow ring is no longer available and the Nightly ring no longer checks for updates.
- [x] #1346 The extended changelog has been removed.

## Bugfixes
- [x] #1338 Out-of-date versions of Bootstrap have been replaced with Bootstrap 3.3.5.
- [x] #1352 Fixes a bug that caused the Backstage to incorrectly identify the config.php file.
