### ISSUE TITLE
Luna 1.1.2 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1349]
Luna 1.1.2 is the second minor update to Bittersweet Shimmer and comes with some small improvements.

## Improvements
- [x] #1344 The Slow ring is no longer available and the Nightly ring no longer checks for updates0
- [x] #1348 The extended changelog has been removed0

## Bugfixes
- [ ] #1327 Fixes an issue with SMTP Authentication.
- [x] #1328 The avatar dimension limit is shown in the modal again.
- [x] #1333 Fixes a design flaw in error walls.
- [x] #1339 Out-of-date versions of Bootstrap have been replaced with Bootstrap 3.3.5.
- [x] #1351 Fixes a bug that caused the Backstage to incorrectly identify the config.php file
