### ISSUE TITLE
Luna 1.1.4 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1380]
Luna 1.1.4 is a minor release focused on bug fixes and a security issue.

## Security
- [x] #1375 A flaw has been solved that would make it possible for users to mark topics as pinned or close/open them.

## Bug fixes
- [x] #1285 Fixes a bug that will cause messages to not be marked as read in Inbox.
- [x] #1330 Fixes a bug with plurals in the translation files.
- [x] #1358 Fixes a bug that would make unread forums impossible to read in night mode.
- [x] #1360 Fixes a bug in forum_list_accents().
- [x] #1377 Fixes a bug that would make the users online list impossible to read in responsive mode.
