### ISSUE TITLE
Luna 1.2.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1413]
Minor bugfix update for Luna 1.2 Cornflower Blue. Contains quality improvements and more.

## Enhancements
- [x] #1416 Replaced JavaScript redirects with PHP.

## Security
- [x] #1418 Fixes a security issue with deleting avatars.

## Bug fixes
- [x] #1411 Fixes multiple issues with language files
- [x] #1412 Fixes a bug in the PostgreSQL database layer.
- [x] #1415 Fixes a visual glitch on the user page in Fifteen.
