### ISSUE TITLE
Luna 1.3 "Denim" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1414]
Luna 1.3 Denim an update that mainly focusses on improving minor things and rewrite major parts of the CSS and HTML of Luna.

## Features
- [x] #1419 **New "New" label**: Rework the [ New ] label to match other labels.
- [x] #1420 **Mark as important**: You can now mark a thread as "important", similar to pins, but they don't stay on top.
- [x] #1435 **Center text**: Luna now has an optional opt-in center tag.
- [x] #1436 **Size text**: Luna now has an optional opt-int size tag.

## Enhancements
- [x] #1421 **Redirect opt-out**: Luna will no longer provide an opt-out for leaving a redirect to a thread, instead it's an opt-in now.
- [x] #1424 **Backstage for mobile**: the Backstage has received a number of enhancements to improve its mobile interface for small screens.
- [x] #1434 **Embedded videos**: embedded videos no longer have a width and height set and will instead be responsive to the area available.
- [x] #1437 **High-DPI support**: Luna has been improved to be more High-DPI friendly.
- [x] #1448 **Thread profile settings**: the thread profile settings have been cleaned up to be more obvious.
- [x] The behavior of multiple markup tags has been changed to be more logical and prevent issues with parsing.

## System
- [x] #1425 **Timezones**: the whole timezone and DST system has been reworked, DST is now handled by itself, however this does reset your Timezone.

## CSS and PHP improvements
- [x] #1371 **Coding conventions update**: as we've finally added our CSS coding conventions, it's time to apply them for Improved readability.
- [x] #1387 **Revamped naming scheme**: the database has received a massive update to realign our naming scheme.

## Fifteen and Sunrise
- [x] #1334 **Sunrise 2.0**: Sunrise is no longer based on Fifteen and now provides a brand new interface.
- [x] #1409 Fifteen now shows categories in the forum list.
- [x] #1410 Fifteen now shows search view at the bottom of the forum list like New, Active and Unanswered.
- [x] #1423 **Better for mobile**: Improve the mobile interface of Fifteen.

## Components
- [x] #1438 **Font Awesome 4.5.0**: update Font Awesome from version 4.4.0 to 4.5.0.
- [x] #1439 **Bootstrap 3.3.6**: update Bootstrap from version 3.3.5 to 3.3.6.

## Bug fixes
- [x] #1432 Fixes an issue with bright colors in night mode for Sunrise.
- [x] #1440 Fixes a visual bug with announcements in Sunrise.
- [x] #1442 Fixes users having a "null" for their comment count instead of a "0".
- [x] #1443 Fixes a markup issue in the contact-panel of the profile.
- [x] #1445 Fixes a visual glitch in the search button on the userlist page in both Fifteen and Sunrise.
- [x] #1447 Drops code that would parse the signature twice.
- [x] Fixes a migration issue from older versions of Luna.
