### ISSUE TITLE
Luna 2.0 Emerald Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1454]
Luna 2.0 Emerald will be the final (for now) Luna release based on the old core, mainly focusing on its new default design based on Airalin, the default design from Luna 3.

## Features
- [x] #1456 Clean up the notification system, enough is enough.
- [x] #1505 Allow admins to upload their own custom placeholder avatar.
- [x] #1506 Allow admins to upload a header image (not a logo).
- [x] #1511 Implement the quick comment field in Inbox threads.
- [x] #1516 Users can now subscribe to forums again.
- [x] #1523 The notification center can now handle individual notifications.

## Mainstage
- [x] Improve the editor to no longer just remove elements, just hide them.
- [x] #1501 Improve contrast for Night mode in Fifteen.

## Backstage
- [x] #1503 Improve the Backstage night mode to better fit like the Fifteen version.
- [x] #1507 Cleaned up statistics panel to be correctly centered.
- [x] Backport some of the design ideas from Luna 2.0's Backstage for a fresher UI.

## Theme and UI
- [x] #1455 Improve search results to better match thread lists.
- [x] #1483 Hide the indent for "Has posted" when not in use.
- [x] #1497 Back-port the forum list from Luna 2 - Fifteen 2.0.
- [x] #1499 Backport Airalin's original draft to Luna 1.x, it's almost entirely compatible, though it does require a couple of HTML and CSS changes and additions.
- [x] #1504 Add support for Custom CSS.
- [x] #1509 Notifications for Inbox now light up the Inbox icon.
- [x] #1510 Include new colors for Fifteen and Sunrise (brown, dark red?).
- [x] #1517 Rebuild Sunrise to be a child of Fifteen and use more of its assets - Sunrise 3.0.

## System
- [x] #1496 Improve SQLite 3 support (fixing some issues, refining the thing, contains also other bugs).
- [ ] #1498 Use forum and board information as filler for meta tags to prevent weird search results.
- [x] #1500 Save passwords more securely, backport Luna 2.0's new password system.
- [x] #1502 Include a Dutch translation, start of making Luna more global.
- [x] #1508 Drops fallbacks for PHP 5.2.x and earlier that are no longer required with the 5.3 system requirement.
- [x] #1524 Use Luna 2's vendor package instead of separate frameworks.

## Bug fixes
- [x] #1463 The login modal on the search page will no longer appear larger on iPads.
- [x] #1512 Fixes missing comment id in comments on Fifteen.
- [x] #1513 Drops extra h4-tag in footer.
- [x] #1514 Drops an extra div-tag.
- [x] #1518 Fixes extra span tag.
- [x] #1519 Fixes an issue where the admin wouldn't get created due to the missing style column.
- [x] #1520 Fix a couple of warnings and undefined variable.
- [x] #1522 Replace Dutch string with English.
- [x] Fixes an issue where the "Compose" button would be hard to see in Fifteen.
