### ISSUE TITLE
Luna 1.3.1 shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1459]
Luna 1.3.1 is a minor update that's all about refining the Luna 1.3 update. It comes with bug fixes and a series of minor improvements on multiple locations within the software.

## Improvements
- [x] #1452 Labels are now more consistent in order on all locations. Furthermore, the search results will now also show the solved- and important-label.
- [ ] #1456 We've reversed the sort order for the notification-fly-out to new to old to match the actual page's order.
- [x] #1457 Improved support for smaller screens and reordered meta tags to apply to Bootstrap's rules.
- [x] #1458 We've improved the moderation interfaces thread listings.
- [x] #1465 Added a "Show subscriptions" button to the profile for users.
- [x] #1470 The "Upload avatar" settings will be hidden when avatars are disabled.
- [x] #1471 The signature-related settings will be hidden when signatures are disabled.
- [x] #1473 The signature checkbox now refers to signature settings for more options.
- [x] #1475 When a group doesn't have search permission, we'll hide the search bar in the header.
- [x] #1476 When advanced search is not available, the button will be hidden.
- [x] #1477 When user search is not available, the search field will be hidden.
- [x] #1480 Hide subscription settings when subscriptions are disabled.
- [x] #1482 Announcements will now appear on the top of the page on mobile devices.
- [x] Sunrise 2 has now a more refined look for its buttons.
- [x] We've removed hundreds of instances where a space or tab was the last character in a line.

## Bug fixes
- [x] #1449 Fixes an issue that would cause the minutes in a notification in the notification-fly-out to not have a leading zero.
- [x] #1450 Fixes an issue where the installer would assign an invalid value to the announcement_type setting.
- [x] #1451 #1453 #1467 #1469 #1474 #1479 Fixes small language issues.
- [x] #1461 Fixes an issue that caused the "mark as read"-links to not work in some situations.
- [x] #1462 Fixes an issue where a banned user would get an error when trying to login.
- [ ] #1463 Fixes an issue where the login modal would be larger in Safari on the iPad.
- [x] #1466 Fixes an issue where changing the thread's state would cause an error.
- [x] #1468 Fixes missing spaces in a comment report.
- [x] #1478 Fixes a double horizontal line that would show up when search was disabled.
- [x] #1481 Fixes a trailing dot at the end of search results on mobile pages.
- [x] We've fixed an issue where the updater would attempt twice to make the same column.
