### ISSUE TITLE
Luna 2.0.2 shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1605]
Luna 2.0.2 is the second minor update for Luna 2.0 that will make a set of minor changes and improvements.

## Improvements
- [x] 01beac8f17c2eaf3aa45b64f08b75b4151393c64 Improves design consistency for errors in Inbox.
- [x] 3b67897b27b0a4e59ce98ae0b1a09748c6938b82 Custom CSS is now loaded before emoji's get their style to allow imports.

## Other changes
- [x] #1607 jQuery has been updated from version 2.2.3 to version 2.2.4.
- [x] 09bd9658161432d551ddeee06c94c12546fd7785 The "We've got us a situation." message has been replaced with "Info".

## Bug fixes
- [x] #1603 The inline comment section for Inbox shows a "The user has left the conversation" error.
- [x] #1606 The reset password link is invalid in new emails.
