### ISSUE TITLE
Luna 2.0.6 ship list

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1628]
Luna twoo.ho.six is a minor patch release to fix a number of bugs found in Luna 2.0.5.

### And further
- [x] #1633 When a thread is hiden, it will now show a yellow indication on the right hand side.

### Bug fixes
- [x] #1624 The Mainstage will show the list of notifications twice.
- [x] #1625 Some BBCode tags might break with specific use of hard returns.
- [x] #1626 Spoilers are unreadable in night mode.
- [x] #1627 Editing an user as admin/moderator will change the accent to the admin/moderator his/hers accent.
- [x] #1630 The sorting on the userlist page is incorrect when navigating to the second page.
- [x] #1631 Forums available to moderate aren't show on the admin settings page in profiles.
- [x] #1632 Undisclosed security issue.
