### ISSUE TITLE
Luna 2.0.8 ship list

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1652]
It has been a long time and Luna 2.0.8 is supposed to fix all problems that have come into view over the past (nearly) 2 years.

## Components
- [x] #1639 Update Font Awesome from version 4.6.3 to version 4.7.
- [x] #1651 Update Prism from version 11.0 to version 14.0.

## Bug fixes
- [x] #1646 Fixes an issue where splitting a thread would reset solved to null.
- [x] #1650 Replace all errors thrown by PHP 7.2 due to deprecations.
- [x] #1657 When an issue occurs with uploading images in the Backstage, it will no longer use Mainstage errors.
