### ISSUE TITLE
Luna 2.0.9 ship list

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1666]
# Luna 2.0.9

Luna 2.0.9 is a minor update, bringing mostly improved support for PHP 7.2 and a number of bugfixes.

## Enhancements
- [x] #1659 **Site description**: you're site description can now be up to 300 characters long (up from 255).
- [x] #1663 **Profile-based time formatting**: the profile now takes the users timezone into consideration when showing time and date.
- [x] #1665 **Search errors**: improved descriptions for search errors.

## Git and GitHub
- [x] #1672 **Generated downloads**: GitHub will now ignore some files that aren't part of Luna when generating downloadable versions of tagged releases.
- [x] #1673 **Include License**: the GPL v2 License is now included in the repository.
- [x] #1674 **Issue templates**: when creating a new issue, you can now start with a template.
- [x] #1675 **Pull request template**: when creating a pull request, you can now start with a template.
- [x] #1676 **Code of conduct**: a code of conduct has been added to our repository.
- [x] **Contribution guidelines**: contribution guidelines have been added to our repository.

## Fixed issues
- [x] #1660 Underscores are now properly escaped in `LIKE`-queries.
- [x] #1661 Fixes an issue where SMTP data could not be properly saved due to a to low character limit.
- [x] #1662 Calculations in debug-mode can now be finished properly regardless of localization.
- [x] #1664 There is no longer a hardcoded "said" string in `bbcode2email()`.
- [x] #1667 The forum title will no longer appear to far to the left when active.
- [x] #1668 A space has been added to quote titles before "wrote".
- [x] #1669 `spoiler` is now properly quoted in the parser.
- [x] #1670 Night mode now correctly colors the border in the release notes.
