### ISSUE TITLE
Installable themes

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1688]
Starting with Luna 2.1, themes will have to be installed, with this a lot of new options are made available to themes.

## Backstage
- [x] #1685 Theme selection has been moved to its own page titles "Theme".
- [x] The "Theme" page has been renamed "Appearance".
- [x] Features not supported by a theme are now marked as such.
- [x] Theme can now be removed from the file system from within the Backstage.
- [ ] Theme settings are now available if a theme has them.

## Themes
- [x] #1677 The `information.php` file has been replaced with `theme.json`.
- [x] #1678 Themes can now declare which features they supported in their json declaration.
- [x] Themes can now declare their accent colors in their json declaration.
- [x] Themes can now add configurations to the `config`-table when installed.
- [ ] Theme can now declare the various settings they have in their json declaration.
