### ISSUE TITLE
Luna 2.0.10 ship list

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1694]
Luna 2.0.10 is a minor maintenance release to fix a number of issues.

## Changes
- [x] #1692 Luna will now update the `o_cookie_bar_url` value to match the new site when the default URL is being used.

## Fixed
- [x] #1690 `LUNA_DEBUG` now works properly for PostgreSQL installations.
- [x] #1691 Changing the default user group now works again.
- [x] #1693 Upgrading Luna 1.x or lower to Luna 2.0 or higher will no longer set `o_custom_css` to `"NULL"` instead of `NULL`
- [x] #1695 Fixes a PHP error with receivers in Inbox not being countable
- [x] #1696 The paper plane icons in Inbox are now properly alligned
