### ISSUE TITLE
Luna 2.0.12 ship list

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#1705]
Luna 2.0.12 is a security releases which also introduces a number of other fixes and enhancements.

## Features
- [x] #1699 Updates emoji to match remapped emoji from Luna 2.1, as well as introducing support for modern emoji shortcodes.

## Fixed
- [x] #1700 Luna now returns a HTTP/503 code when in maintenance mode.
- [x] #1707 Luna no longer returns the password when a registration error occurs.
- [x] #1712 Luna will now properly migrate the database when fields are being dropped.
