### ISSUE TITLE
ModernBB is broken

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#186]
Somewhere during ModernBB 1.6.2 development, we've accidentaly merged a part of ModernBB 2.0 beta. Sadly enough, we've got to start from ModernBB 1.6.1 code and do all changes in ModernBB 1.6.2 all over again. Making this ticket, a hotfix.
- [x] #45 - security Referrer check breaks with UTF-8 URLs
- [x] #57 - Moderators can edit Admin's posts
- [x] #58 - Broken PostgreSQL support on 1.5.1+ with o_redirect_delay == 0
- [x] #93 - Problem with PHP_EOL constant and email.php
- [x] #106 - When no forums, statistics are wrong displayed
- [x] #120 - Strict standards error in PostgreSQL adapter
- [x] #123 - forum administration
- [x] #124 - Caching breaks on concurrent access, possible information disclosure
- [x] #125 - When update is unable to add o_base_url, it gives wrong warning
- [x] #126 - security Escaping admin's mail
- [x] #128 - security Redirect URL after email dialog not verified
