### ISSUE TITLE
Redesign default styles

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#200]
The current default styles are kinda ugly, ModernBB 2.1 will improve them a lot.
## Planning designs

ModernBB 2.1 will feature 3 default styles, instead of 4. The yellow design, Kindness, will be gone from the default installations. However, Kindness will become part of a pack of other styles, including a black, with, purple, pink and orange version of Randomness, this will be released in the future, after ModernBB 2.1 is finished (or at least its beta).
## To-do
- [x] **Randomness** the default blue style.
- [x] **Radicalness** the red version
- [x] **Awesomness** the green version
