### ISSUE TITLE
Revamp profile interface

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#247]
# Profile interface

The current profile interface contains 8 sections. 6 are options, 1 is "View profile" and the last one is for administrators and moderators only. This is far from ideal.
# Concept

This is how the profile currenlty looks like:
![Profile](http://www.imgdumper.nl/uploads7/525a63487634c/525a63486caf6-current.png)

This is what is going to supposed to look like. Note that this is a concept and the final version might look different.
![Profile 2.2](http://www.imgdumper.nl/uploads7/525edcfe11c50/525edcfe04d49-update.png)
# Goals and structure

The goal of the new interface is to simplify the way users have to work with it. We want a simple structure:
## Structure
- **Profile:** the "Profile"-page will be the landing page. This page can be seen by everyone: guests, users, moderators and administrators. It contains all information from the current "View profile" tab.
- **Contact:** this page will be displayed when users want to contact other users. It's the same page as the one that can be accessed trough the "Mail" link in topicview.
- **Settings:** this page contains all settings, all the content from the current "Essentials", "Personal", "Display", "Messaging" and "Personality" page are included in this.
- **Administration:** contains the same information as the current "Administration" tab, it's probably the only tab that doesn't have to change.
## Goals
- The general information has to be easly visible.
- The current Profile page doesn't show on every page which user you are actualy looking at, this should be fixed (for admins and mods, this is very anoying).
# Issues
- [ ] #264 Revamp the profile (design)
- [ ] #263 Revamp the profile (interface)
- [x] #269 Revamp the profile (system)
