### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#261]
Make the ModernBB styles responsive by default. This ticket will be extended soon.
# Issues
- [x] #278 Remove code that blocks responsive design
- [x] #283 Add hamburger buttons to navbars
- [x] #296 Disable hover-dropdown in front-end, enable in Backstage
## Frontend only
- [x] #289 Fix header responsiveness
- [x] #292 Update styles to be responsive
- [x] #293 Replace _-xs-_ classes with _-lg-_ in frontend
- [x] #294 Hide elements when responsive design is used
## Backstage only
- [x] #274 Make Backstage Responsive
- [x] #281 Replace _-xs-_ classes with _-lg-_ in Backstage
- [x] #282 Update Backstage style to work correctly with new code
- [x] Update Backstage design
- [x] #295 Dropdown menus color is black on hover
## Installation
- [x] #291 Update installation interface to be responsive
## Login and updating form
- [x] #297 An even more simple login and update experience
