### ISSUE TITLE
ModernBB 2.2 "Zoe" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#303]
This is the shiplist, kind of an advanced version of our changelog, for ModernBB 2.2. The main focus in ModernBB 2.2 is on 3 points: responsive design, profile interface and the backstage. Further are small changes, little new features and of course bugfixes. ModernBB 2.2 is planned to be released in the Winter of 2014, a beta should be available as soon as december 2013. However, do not pin us on those dates.
# Features
### Responsive design

In ModernBB 2.2, we've worked hard on a _responsive design_. This was our primary goal for this release and is forum-wide. That means: it's in the Backstage and frontend.
- [x] #261 Make ModernBB responsive everywhere.
- [x] #274 Make Backstage responsive, allow it to be used on every device.
- [x] #278 Remove code that blocks the use of a responsive design, this was added to fix bugs in earlier versions, now, it's unneeded.
- [x] #281 #293 Replace classes that disable responsive designs in the Backstage
- [x] #283 Add hamburger buttons to navbars, they aren't available everywhere.
- [x] #289 The header in the front-end isn't responsive.
- [x] #291 Update the installer to be responsive, like everything else.
- [x] #292 Update Randomness, Radicalness and Awesomeness to be responsive.
- [x] #294 Hide elements that are useless when the design is responsive.
- [x] #318 Update Backstage style to be able to handel responsive design.
### Profile interface

The _profile interface_ of FluxBB, and so ModernBB, is horrible. In ModernBB 2.0, we added a temporary solution for a serious issue in this view, in ModernBB 2.2, we're fixing it permanently.
- [x] #247 Revamp the profile interface.
- [x] #263 Create a new interface for the profile.
- [x] #264 Recreate the design, not to be confused with #263.
- [x] #269 Create a brand new system for the profiles.
- [x] #273 To be shown optimal, avatars should be bigger by default.
### Backstage

A last-minute focus point. We want to clean up the Backstage a little bit more. We did some great work in version 2.1, however, we will extend the changes now further.
- [x] #282 The Backstage style has had a small update, the Backstage is now wider to display content better. We also did small changes to the design.
- [x] #319 We've improved the markup of the update checker, handy for ModernBB 3.
- [x] #327 The Backstage interface makes now more use of Bootstrap features.
- [x] #328 We removed even more tables in favor of a responsive capable structure.
- [x] #352 The update checker is now capable of warning you when you are using a version that is released after the last stable release.
- [x] #370 We've removed the about page, in favor of a link to the documentation.
### Others
- [x] #284 The "Forums" page is no longer available when there are no categories.
- [x] #299 The parser now supports font-family, font-size and horizontal dividers.
- [x] #325 ModernBB 2.2 features new default designes, Randomness, Radicalness and Awesomness have been updated, and are way lighter then before!
# Changes
- [x] #271 Bootstrap has been updated to version 3.0.1.
- [x] #272 The login form no longer shows "ModernBB" in the login form, but simply "Login".
- [x] #279 Update the "Last edited" line, smaller and lighter.
- [x] #296 Both the login and update interface have been redesigned to give a more modern look.
- [x] #298 The Advanced Search interface looks horrible, time for an update.
- [x] #301 The registration form no longer shows that a field is required, of course, it is still required.
- [x] #304 Display "Moved", "Sticky" and "Closed" as labels.
- [x] #305 Display indicators below textfields are now displayed as labels.
- [x] #306 The paginations now use the Boostrap pagination.
- [x] #307 "Registered" has been removed from the topic view.
- [x] #310 "Post new topic" has been given a button style.
- [x] #312 The "IP Address Logged" and "Email" link have been relocated to the posts Action Bar, left hand side.
- [x] #316 Bootstrap has been updated to version 3.0.2.
- [x] #323 We've removed unused images from the style folder.
- [x] #324 The default styles no longer use browser specific code.
- [x] #348 Files with other names then their actual title in ModernBB, have been renamed.
- [x] #355 Pagination is now Always visible.
- [x] #361 Drop support for font markup in parser.
- [x] #363 Buttons that need it, are now placed in a btn-group.
- [x] #364 Groups settings save button has been put in header.
# Bugfixes
- [x] #274 Fixes a bug that makes it inpossible to install ModernBB.
- [x] #290 Fixes some bugs in the navbars in both frontend as Backstage.
- [x] #295 Dropdown menus in the Backstage where black on hover.
- [x] #296 When colapsed in the hamburger menu, a mousover would still show a dropdown-styled menu.
- [x] #302 The login link is displayed to far to the right on the front-end.
- [x] #300 On the index, instead of "Posts", the bars showed "Posts:".
- [x] #308 On the forumview, instead of "Replies", the bars showed "Replies:". Related to #300.
- [x] #309 There is no padding set for the "Post review"-panel.
- [x] #322 Action bar displays action more then once
- [x] #326 The issue that prevent admins and mods from searching on "other people with the same IP address" has been fixed.
- [x] #329 Permissions.php can now be translated completely.
- [x] #332 Fix some minor issues in ModernBB.
- [x] #335 We're using better language variables now.
- [x] #338 Remove obsolete global variable.
- [x] #341 Fix various UTF-8 issues.
- [x] #349 We've fixed mutliple issues in the navbar.
- [x] #353 Settings can be saved again in the new profile view.
- [x] #356 The inline pagination in forum view has been fixed.
- [x] #358 Use require_once to make sure function is not loaded twice.
