### ISSUE TITLE
ModernBB 3.0 "Odd" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#313]
ModernBB 3 will be a major update to ModernBB, you won't see as many difference as you saw with 1.6 to 2.0, but it will be a great release. The Backstage will get a new style and we will improve the structure of the Backstage. We've got some nice under-the-hood changes ready for all of you guys. I suggest you read the full changelog below:
### Backstage
- [x] #351 Merge "Categories" and "Forums".
- [x] #469 The Backstage design has been updated: less shadows, more contrast, perhaps a new (default) color scheme.
- [x] #473 The Groups page also contains checkboxes instead of radio buttons now.
- [x] #487 The "Advanced Bans" interface now also features the new interface introduced in ModernBB 2.2.0.
- [x] #510 The board description field no longer contains p and span tags (by default).
- [x] #513 Revamp the structure of the Backstage.
- [x] #514 Support different color schemes in the Backstage.
- [x] #516 We've removed a lot of inconsistent design.
- [x] #537 We've applyed the btn-danger style to buttons that are potential dangerous to hit.
- [x] #555 The update system has been refactored to work better, it can't load anymore without loading the required data and now uses its own cache system. The updates will check for updates every day automaticaly.
- [x] The server statistics page's design has been altered.
### Setup
- [x] #217 Remove password request when updating.
- [x] #371 Updates has been added as a tab on the Backstage index.
- [x] #548 The installation uses a better interface now.
- [x] #556 A new feature, called "Soft reset" is added and will be used to remove the config.php file if required.
- [x] #557 A new feature, called "Hard reset" is added that will remove the database and config.php file.
- [x] We've fixed some design flaws in the installer.
#### Database
- [x] #244 Implementate the SQLite 3 layer in db_layer.php.
- [x] #367 We do not support PostgreSQL anymore.
- [x] #522 Support for MariaDB has been dropped.
#### Features
- [x] #320 It's now possible to disable the header description without leaving the Description-field blank in the Backstage.
- [x] #420 The "email" label is now hidden in the request password form.
- [x] #477 The pagination function now uses span-tags for disabled and active states.
- [x] #479 `<span class="sr-only">(current)</span>` hasb een added to the current page in pagination.
- [x] #485 The debug information table has been styled.
- [x] #506 It is now possible to disable that statistics panel on the frontend.
- [x] #521 The last active topic' subject is now displayed on the index.
- [x] #546 Labels in post.php are now clickable.
- [x] #574 When moderating a topic, you can now select 'All' to show all posts in that topi
- [x] #587 The alignment menu has been removed from the editor.
- [x] #594 The editor is only shown there where it is needed.
- [x] The user search form has been improved and takes less space now.
#### Design
- [x] #368 The action bar is now compacter.
- [x] #435 The login form and update form now use the default design of the frontend, rather then the Backstage design.
- [x] #499 Select checkboxes are moved to the right in moderate.php.
- [x] #530 The front-end now also uses header buttons for easier access to save settings.
- [x] #536 The interface of the registration page has been updated with a better and slimmer interface.
- [x] #545 Quickpost has been redesigned with a better interface, for registrated users and guest users.
- [x] #546 Post.php has been redesigned to match the quickpost field.
- [x] #554 The email page has been updated with a new interface.
- [x] #561 The topic title is now displayed in a H2 tag to make it more clear what topic is open.
- [x] #580 The edit page has been updated with the new interface from post.php.
- [x] #591 The report interface has been improved.
- [x] #607 The action bar has now a less distracting design.
#### Styles
- [x] #484 Colums like "Posts", "Replies" and "Views" are now centered.
- [x] #520 Kindness is a new theme based on Randomness, it's yellow sister from ModernBB 2.0.
- [x] #551 Give active state in menu a color between title and navbar in Randomness, like other styles.
- [x] #566 The error() function displays now nice errors instead of those ugly ones.
- [x] #604 The toggles (hamburger menu buttons in responsive design) now feature a better design.
### Editor and parser
- [x] #287 Add new editor to ModernBB.
- [x] #288 Remove the old toolbar and remove all database information.
- [x] #519 The parser now support inline code tags, the c-tag, this doesn't support syntac highlithing.
- [x] #535 Support for acronyms has been dropped since this isn't part of the standard anymore.
- [x] #579 We now support H1, H2, H3, H4, H5 and H6 as new header tags. H will produce H4.
- [x] #582 Update TinyMCE design to blend in with ModernBB.
### Others
- [x] #507 The maintenance page has been updated with a new style.
- [x] #565 The confirm_refferer() function has returned for Improved security.
- [x] #586 Multiple improvements on the responsive design have been done.
- [x] #606 When editing a post, the "Global Settings" checkbox labels are now clickable.
## Changes
- [x] #369 The size attributes have been removed, instead, we now use Bootstrap classes.
- [x] #457 Breadcrumbs are now ordered lists.
- [x] #512 If you want to update from FluxBB to ModernBB, at least FluxBB 1.5.0 is required.
- [x] #527 Non array page titles are now supported for plugins from FluxBB 1.2 or lower.
- [x] #532 The username is now displayed as title for the Profile instead of "Profile".
- [x] #564 We've taken a serious look at the language file and cleaned it up.
- [x] #577 Support for Internet Explorer 8 has been dropped, IE9 and higher are required from now on.
- [x] #595 All pun_ code has been renamed to luna_ for compatibility with Luna later on.
- [x] The help page has been cleaned up for better navigation.
## Components
- [x] #317 Bootstrap has been updated to version 3.0.2.
- [x] #460 Bootstrap has been updated to version 3.0.3.
- [x] #524 jQuery has been updated to version 2.0.3.
- [x] #525 Bootstrap has been updated to version 3.1.0.
- [x] #534 jQuery has been updated to version 2.1.0.
- [x] #541 Add Bootstrap font to core for icons.
- [x] #552 Include TinyMCE 4.0.12 for the editor.
- [x] #598 Bootstrap has been updated to version 3.1.1.
## Bugfixes
- [x] #379 "Go back" buttons now do no longer have a clear button style, but are button links, due to a issue with Firefox.
- [x] #488 Fixed fonts for some browsers and iPad.
- [x] #518 Empty list for status info when guests
- [x] #526 Board structures only showed settings when 2 or more categories where created.
- [x] #538 Buttons on the group page are now btn-groups.
- [x] #539 IDs are now unique on multiple pages.
- [x] #544 The user information span won't be shown when user information is disabled.
- [x] #549 Antispam API can be saved again.
- [x] #572 Fix colspan bug in viewtopic.php
- [x] #575 Textareas can now only be resized verticaly.
- [x] #581 The double click issue in the editor has been fixed.
- [x] #583 TinyMCE will no longer remove hard returns when editing.
- [x] #584 It's now possible to use emoticons again without bugs in the parser.
- [x] #585 Edit.php now gives the right interface when editing a topic starter.
- [x] #590 Lineheight in post, edit and email textboxes has been increased so text is no longer cutoff.
- [x] #592 The icons in the Backstage do not show up anymore.
- [x] #593 We've fixed an issue that occured with Bootstrap 3.1.0.
- [x] #597 We've removed the cols attribute from textareas, since this now works with Bootstrap.
- [x] #603 The IMG tag now can be used without issues in the WYSIWYG editor.
- [x] #605 The WYSIWYG editor is now also showed when editing a post and in the quick post view.
## Tasks
- [x] #540 ModernBB now uses the MIT license instead of the GPL v3 license.
- [x] Merge all changes that have been done in other branches, we're currently on MMB 2.2-beta in this branch.
- [x] Remove the Bootstrap theme from the core in beta 1.
