### ISSUE TITLE
ModernBB 2.2.3 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#500]
ModernBB 2.2.3 is a small update and the first of its kind. There is no specific point this release focus' on. It rather contains small improvement all trough the forum software. This is, by the way, the magical #500 ticket and might eventual turn into the changelog of the release.
### Backstage
- [x] #487 The "Advanced Bans" interface now also features the new interface introduced in ModernBB 2.2.0.
## Bugfixes
- [x] #518 Emtpy list for status info when guest
- [x] #572 Colspan has been fixed in viewtopic.php
