### ISSUE TITLE
ModernBB 3.1 "Mellow" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#600]
ModernBB 3.1 is going to be a rather small update, however, visualy you will notice changes here and there! ModernBB 3.1 is supposed to hit you early April 2014. It's named "Mellow".
### Setup and installation
- [x] #614 Our versioning system has been changed to that of Vanellope for easier versioning.
### Security
- [x] #611 Passwords are now required to have 6 characters instead of 4.
- [x] #612 The version number of the installation will no longer be displayed when installing ModernBB by default.
### Design
- [x] #596 The editors' style now fits better with the ModernBB design.
- [x] #613 The topic view has been updated to a Vanellope-like design for Improved topic reading.
- [x] #616 The "Change password" screen has been updated with a better interface.
- [x] #618 We've Improved the way the statistics are displayed on the frontpage.
### Features
- [x] #350 We've improved the unreaded forums tracking system for better performances on larger forums.
- [x] #576 When creating a new topic and "Preview" is hit, the title is now also showed in the breadcrumbs.
- [x] #619 When a link is opened within a post, it now opens in a new tab.
- [x] #622 We now use a placeholder for people without an avatar.
- [x] #623 The usermenu has been redesigned with brand new possibilities.
- [x] #624 If you like, you can now disable "Index", "Search" and "User list" links in the menu bar.
### Components
- [x] #615 Update TinyMCE to version 4.0.20.
### Bugs
- [x] #608 All texts can now be translated again.
- [x] #609 The login and registration button are now displayed correctly on the navbar.
- [x] #617 We've fixed multiple issues with the navbar when it's collapsed.
- [x] We've fixed a padding issue with the footer.
