### ISSUE TITLE
ModernBB 3.2 "Mellow" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#628]
ModernBB 3.2 "Mellow" is the second Mellow-release and will feature improvements to a couple of sections of the ModernBB software, the help-page, user list and profiles will be redesigned with awesome new features.
### New features
- [x] #578 Users can now see in which topics they have posted.
- [x] #629 The Help-page has been updated with new and improved information.
- [x] #642 We've added the new purple "Magic" style, based on Randomness.
- [x] #654 New users will now get a "first-run" dialogue that explains the basics of ModernBB to them.
- [x] #663 Default Time and Date notation are now part of the language files.
- [x] #684 We've added the new orange "Happy" style, based on Randomness.
### Design
- [x] #627 The profile interface has been redesigned completely.
- [x] #649 Decrease the size of the default styles, change some of the design elements.
- [x] #665 The userlist now shows avatars and has had a general redesign.
- [x] #668 The index page is improved to be more content-friendly.
- [x] #669 We've reworked the forum view.
### Changes
- [x] #643 Breadcrumbs have been improved to be more touch friendly.
- [x] #650 After adding a new forum, you will be redirected to the "Edit forum" page.
- [x] #655 We've removed all redirect screens to give you a faster experience.
- [x] #662 We've removed some parser features that aren't used anymore.
- [x] #679 Remove the () from moderated by list.
- [x] #680 When users have registered in PunBB 1.2 or lower and not loged in since you updated to anything newer, they won't be able to update anymore due to a code cleanup in the login script.
### Improvements
- [x] #626 #630 We've cleaned up our language files.
- [x] #645 The moderation bar is now more accessable with icons, color codes and less used space.
- [x] #647 It's now possible for the Backstage to load db_update.php from itselfs.
- [x] #648 We've removed a lot of code from the profile page to improve the system itself.
- [x] #664 The WYSIWYG editor now shows an underline and strikethrough option.
- [x] #682 The link behind the update mechanism has been updated.
### Bugfixes
- [x] #641 The values in the "Search in" dropdown aren't displayed bold anymore.
- [x] #646 The signature field is now not bold anymore.
- [x] #651 Radicalness, Awesomeness and Kindness can now handle the new user menus correctly.
- [x] #652 We've fixed an issue with the navbars index button in combination with the user list.
- [x] #653 Replace &amp; with & where needed.
- [x] #656 We've fixed the wrong navbar-brand color in Randicalness.
- [x] #659 A markup issue after a failed validation has been fixed.
- [x] #666 When a H1 is added, it won't show to high anymore.
- [x] #667 The db_update.php file can't be loaded anymore.
- [x] #672 We've fixed some bad behavior of the navigation bar.
- [x] #675 User profiles display current user avatar instead of the avatar of the actual user.
- [x] #677 #678 The feedlinks have been fixed, and the code behind them has been improved.
- [x] #683 The signature line is no longer shown when no signature is set and no actions are available.
- [x] #686 We have to escape the username in the first run message.
### Others
- [x] #661 We've added some extra rules to .gitignore. - dev only
### Improvements
- [x] c9e4d36 The menu title will now be displayed by default.
- [x] 81a1f45 We've updated the registration interface to match the new profile settings design.
### Changes
- [x] 46a05a4 e23606a Our default styles have been renamed to Random, Awesome, Radical and Kind to better match with Magic and Happy.
### Bugfixes
- [x] c499f4f We've fixed an issue with the responsive design in the forum view.
- [x] 9dbf4cd Fixed an issue in the language file that caused problems with First run default settings.
- [x] 55fc528 We've fixed the user list avatars preview.
- [x] 9044a3f The groups page will now function again.
- [x] ca17fc6 Fix some language issues in install.php.
- [x] 2410478 Fix more language issues
