### ISSUE TITLE
ModernBB 3.1.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#638]
ModernBB 3.1.1 is a small update for the original 3.1 Mellow update. In this update, we've planned to fix multiple issues and improve the experience in general.
### Improvements
- [x] #637 The code-button has been added to the editor again.
- [x] Some cleanup has been done to the language files.
- [x] We've removed some lines that where supposed to fix issues in Bootstrap 3.0.0.
- [x] We've Improved the way the profile handels responsive design, the menu won't be relocated to the top as quick anymore.
#### Design
- [x] #633 The brand in the navbar isn't highlighted anymore in responsive mode, allowing (slightly) longer titles.
- [x] #634 The header title will no longer be shown in responsive mode.
- [x] The first post on a topic page will not take 10 more pixels for padding anymore.
### Bugfixes
- [x] #631 We've fixed some issues with avatars in the new topic view.
- [x] #632 the "Last post" collum didn't take all available space in responsive mode.
- [x] #635 We've fixed some padding issues in the profile interface.
- [x] #636 Fixed a bug that created issues with lists when editing a post in TinyMCE.
