### ISSUE TITLE
ModernBB 3.3 "Vanellope" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#700]
ModernBB 3.3 is our fancy update to the ModernBB forum software. In this release, we updated the Backstage with a brand new design and a lot of UX improvements and we're also happy to include a brand new and proper style system.
# Tickets
### Backstage
- [x] #560 It's now possible to clear all cache files from the Backstage.
- [x] #670 The Backstage features a brand new design - Aurore 5 - following the 384 Group design guidelines.
- [x] #692 There are now 4 Backstage accent colors available: ModernBB Blue, Lime, Yellow and Red.
- [x] #696 All Bootstrap features are now supported in Aurore 5, the default Backstage design, for developers to use.
- [x] #699 We've added a link to the front-end in Backstage.
- [x] #707 The rules and other textareas in the Backstage now have a TinyMCE interface to make it easier to use!
- [x] #718 We've Improved the mobile interface of the Backstage to better use all available pixels.
### Template and style system
- [x] #689 The logic has been seperated from the views in the front-end.
- [x] #693 The style management has been revamped completely.
- [x] #694 Styles now require more information and another structure to work with ticket #693.
- [x] #713 Styles are now able to use their own emoticonset.
- [x] #715 Styles can now overwrite views.
- [x] #722 Multiple improvements to the style system.
### Other features
- [x] #321 #750 Names in index and forum view are now clickable.
- [x] #674 It's now possible to disable the Advanced search option completely.
- [x] #724 We've added 3 new styles: Shy, Luna and Pinkie.
## Improvements
- [x] #533 The post preview feature now shows a similar design to the topic view.
- [x] #695 We've Improved redirections when adding new posts so they don't repeat.
- [x] #697 The "New user" mail now contains a link to the users administration page.
- [x] #698 The space between the navigation bar and footer has been reduced.
- [x] #701 BBCode indicators do no longer link to the Help page.
- [x] #705 We have seriously reduced the size of our images.
- [x] #708 Quotes are now styled more clearly.
- [x] #711 For more contrast, the first run avatar now has a shadow behind it.
- [x] #717 Only moderators and admins can now see the "Moderating" section in the help page.
- [x] #719 "Settings saved" and other messages will appear again.
- [x] #726 #728 All email templates have been removed in favor of the normal language file.
- [x] #731 The look of buttons in the random style has been Improved.
- [x] #733 The "posted" label has been replaced with an asteriks to be less distracting.
- [x] #734 The labels have a much more sensable order.
- [x] #742 The styles have been updated with an improved responsive design.
- [x] #751 Search results for users in the Backstage are now striped and will light up when hovering.
- [x] #762 The ban page has been updated to follow the design guidelines.
- [x] #763 The installation has been updated to follow the design guidelines.
- [x] Multiple design improvements to styles
- [x] The way borders for panels are loaded in CSS has been drasticaly Improved.
## Components
- [x] Update TinyMCE to the latest version
  - [x] #703 TinyMCE has been updated from version 4.0.20 to 4.0.23.
  - [x] #714 TinyMCE has been updated from version 4.0.23 to 4.0.25.
  - [x] #721 TinyMCE has been updated from version 4.0.25 to 4.0.28.
  - [x] #730 The TinyMCE editors style now matches the post style again.
  - [x] Superscript and subscript are added back to the toolbar in TinyMCE
  - [x] Wordcount has been removed from TinyMCE.
- [x] #716 jQuery has been updated from version 2.1.0 to 2.1.1.
- [x] #735 Bootstrap now uses its default structure.
## Bugfixes
- [x] #505 We've updated the back-up feature to support newer versions of PHP (5.3 and higher).
- [x] #687 We've fixed some of the display issues when going into responsive mode.
- [x] #688 We've removed one of the collons in the Board statistics panel.
- [x] #690 TinyMCE will no longer add html if you copy text from Microsoft Word or other text editors.
- [x] #702 Fixed undefined variable: redirect_url
- [x] #704 The Breadcrumbs in fast search are now displayed correctly
- [x] #706 It's now possible to post relative links again without issues.
- [x] #712 Fixed a missing closing tag in viewtopic
- [x] #720 We've fixed an issue that would remove all pharagraphs when editing posts.
- [x] #723 The breadcrumbs when posting a new topic work properly again.
- [x] #732 Parser won't add spaces for no good reason anymore.
- [x] #736 Fixed a visual bug in the registration form.
- [x] #737 We've fixed a bug that caused the registration form to bug when rules where set.
- [x] #738 The parser can now handle alignment changes correctly.
- [x] #739 The "Forgotten password" page now works again.
- [x] #740 No double p-tags in profile anymore.
- [x] #743 The rules page will show up again.
- [x] #744 We've fixed the issues with lists in TinyMCE.
- [x] #745 We've fixed some issues in the responsive design of the search results.
- [x] #748 The space won't be displayed as &nbsp; anymore when this occured.
- [x] #749 In some situations, posts wouldn't be reported.
- [x] #755 Fix issues with last poster implementation.
- [x] #756 Entities convertion for “…” has  been fixed.
- [x] #759 Guest won't get an error when posting a new topic or post.
- [x] #760 The ID used in the topic search has been corrected.
- [x] #764 Fixed another issue with spaces in TinyMCE.
- [x] #765 When the cache is cleared, there won't appear a 404 error anymore.
# Commits
## Changes
- [x] 16890da The debug table has been improved with new usability features
- [x] 4e469ba The Backstage will no longer trow unstyled messages to you.
## Security
- [x] a4bfaff Only Admins have now access to the reset features
## Bugfixes
- [x] d60baef When changing the group settings for group 1, the groups settings don't reset anymore to 0.
