### ISSUE TITLE
ModernBB 3.2.2 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#741]
ModernBB 3.2.2 is the next minor patch release in the ModernBB 3.2 branch, and we hope it to be the last one (because ModernBB 3.3 will be out there soon).
# Tickets
## Bugfixes
- [x] #738 The parser can now handle alignment changes correctly.
- [x] #740 The double p-tag in profiles have been removed.
- [x] #745 We've fixed some issues in the responsive design of the search results.
