### ISSUE TITLE
ModernBB 3.3.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#770]
Fixing bugs is what we do, and so will ModernBB 3.3.1. Just like every patch release, ModernBB 3.3.1 will fix a couple of issues and bring small improvements.
# Tickets
## Changes
- [x] #773 The langauge file has been enhanced for the help page.
- [x] #774 Guests will now always get the placeholder avatar next to their name in topic view.
- [x] #776 The pagination in the Backstage now also follows the color scheme instead of the blue color it had.
## Bugfixes
- [x] #759 We fixed a syntax issue in post.php.
- [x] #766 When maintenance mode has been enabled, an error would ocure.
- [x] #767 When visiting someone elses profile, settings pages where listened in the profile menu (they are not available, through).
- [x] #768 The poster beside the Quick post field has been fixed and now displays the actual user.
- [x] #769 We've fixed an issue in the user group settings in users.php
- [x] #775 The Studio384 avatar is no longer included in the package on GitHub.com, the downloads on ModernBB.be do not have this issue.
- [x] #777 The styles page is now also open for translation.
# Commits
## Changes
- [x] 54bcc1d The Quickpost field's profile card now shows an online status (which, of course, will always be online).
## Bugfixes
- [x] 0ded9a9 The update dialog now has its style back.
