### ISSUE TITLE
ModernBB 3.4 "Neon" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#785]
ModernBB 3.4 "Neon" is our last rapid-release update, after this, we will go a little bit slower on the development of ModernBB 3.5. This is due to our work on ModernBB 4. No worries, updates to MBB 3.x will be provided.
# Tickets
## Features
- [x] #761 TinyMCE has been removed.
- [x] #778 ModernBB now has a cookie banner that can be enabled in the Backstage > Settings > Global > Cookie bar.
- [x] #784 Some parser features have been removed.
- [x] #794 The profile picture is now shown in the navbar when on the front-end and Backstage.
- [x] #810 Add a BBCode toolbar.
  - [x] #817 When selecting a text and clicking a button, the tags will appear arround the text instead of replacing it.
  - [x] #819 Add toolbar to edit field.
### Backstage > Settings > Appearance
- [x] #780 Under Display settings, a new feature "Show "Moderated by" list" has been added.
### Backstage > Settings > Features
- [x] #796 A new panel "BBCode" has been added.
- [x] #801 Under BBCode, a new feature "Video dimensions" has been added.
### Profile > Settings
- [x] #799 Under Backstage Accent, new colors have been added.
## Changes
- [x] #771 When embedding a video, they will no longer have a border.
- [x] #778 Happy, Magic, Shy, Luna and Pinkie are now available as separate downloads and are no longer included in the ModernBB package.
- [x] #787 The BBCode indicators now link to their help section.
- [x] #790 The "Online:" text is no longer shown when no users are online.
- [x] #793 The default width of an embedded video is now 600 pixels instead of 480 pixels.
- [x] #795 Users are no longer allowed to set their own size for an embedded video of they want to.
- [x] #802 We've Improved the way ModernBB stores passwords.
- [x] #804 Support for Internet Explorer Developer Channel 1.
- [x] #805 The common_admin.php file has been dropped.
## Components
- [x] #729 Bootstrap has been updated from version 3.1.1 to 3.2.0.
- [x] #761 TinyMCE 4.0.28 has been removed.
## Bugfixes
- [x] #753 It's possible again to add videos to your posts.
- [x] #758 There will no longer be extra returns below headinng in the editor.
- [x] #781 An invalid edit preview path has been fixed.
- [x] #782 When registrationg a new user in the Backstage, you get a confirmation message again.
- [x] #783 When 2 or more languages are available, an users now will still be able to register.
- [x] #786 A missing text definition has been added.
- [x] #791 The language string for "Backstage Accent" has been fixed in the profile.
- [x] #797 The "Forum" tab under Help > Moderating can now be accessed again when another tab has been selected.
- [x] #803 Fixed an undefined variable in Add User in the Backstage.
- [x] #806 Fixed a setting when searching users in the user list.
- [x] #808 The "Show images in user signatures" settings can be saved again.
- [x] #809 When changing a setting in profile settings, it won't remove the Backstage Accent anymore.
- [x] #812 Remove extra div-tag.
- [x] #813 When updating to ModernBB 3.4 from any version, the guests style would be wiped out.
- [x] #814 The BBCode indicators aren't lined out well in the post.php page.
- [x] #816 Add a missing closing tag in user list.
- [x] #820 When changing your password, it was inpossible to login.
# Commits
## Changes
- [x] e848b85 The GPL v3 license is no longer included in the package.
- [x] e848b85 The license file is no longer part of the package, instead, we now offer a link to the license on ModernBB.be.
- [x] 5d6ae36 The ModernBB logo has been updated.
- [x] 527a8f4 The unusable SQLite 3 layer has been removed from the core until we've got a working version.
- [x] 48e41a6 If no language file can be found, ModernBB used to go down, now ModernBB will first check of it can load the English language file, if not, than it goes down.
## Bugfixes
- [x] 5bc8e72 A wrong settings when installing ModernBB has been fixed.
# Thanks

There are some people we would like to thank for their colaboration to the ModernBB 3.4 milestone!

@CraigyDavi, @slightlysome, @Studio384 and @Quy!
