### ISSUE TITLE
ModernBB 3.5 "Kate" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#800]
ModernBB 3.5 "Kate" is our newest addition to the ModernBB 3.x series. The focus with this update is mostly on improving the general experience, we don't have a focus point this time arround.
# Tickets
## Features
- [x] #418 The StopForumSpam API integration has been removed.
- [x] #833 PostgreSQL support has been added.
## Backstage
- [x] #839 The Backstage design has been updated.
## Changes
- [x] #827 When creating a new ModernBB installation, ModernBB will add a new forum and category.
- [x] #832 ModernBB 2.0 or higher is required to update to ModernBB 3.5, ModernBB 1.6 and FluxBB 1.5 are no longer supported.
- [x] #844 We've revamped the design of search results when displayed as posts.
- [x] #849 The advanced profile menu has been removed from the navbar.
- [x] #891 A fallback system should prevent ModernBB from failing to load a style.
- [x] #892 When linking to a tab in the help page, this tab will now be active.
- [x] #894 The new FORUM_CORE_VERSION value has been added to ModernBB.
## Components
- [x] #907 Font Awesome has been updated from version 4.1 to 4.2.
## Bugfixes
- [x] #691 We've removed some unrequired markup from the login form.
- [x] #882 Fix a bug that shows a blanc page in users creation.
# Commits
## Changes
- [x] 9d1cc8209fb28f19ef6292d6067779cb8987e090 We've updated a language string.
- [x] b85c80e9d27c020ef311018ed6b210c19d2896c7 "Posted" has been removed from quick search, as there is already a similar option in profile.
## Bugfixes
- [x] a35786a0a6c9c6bfebcfc8ed84e723b288533af2 Fix an error when loading forum view.
