### ISSUE TITLE
ModernBB 3.4.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#822]
ModernBB 3.4.1 is the first in a serie of monthly small feature updates to ModernBB 3.4. We'll keep doing this for this summer, while we're working on ModernBB 3.5 and 4.0.
# Tickets
## Features
- [x] #725 The profiles social fields have been replaced with Facebook, Twitter, Skype and Google+.
- [x] #834 You can now choose from 12 additional colors for the Backstage Accent, others are updated.
- [x] #845 The database back-up now can handle InnoDB too.
### Backstage > Features > General
- [x] #838 It is now possible to disable the post button when in small responsive mode. The button is disabled by default, this also disables the "Preview" button in Quick post.
## Responsive design
- [x] #837 The topic title will no longer be displayed in the breadcrumb when in small responsive mode.
- [x] #839 The Quick post field will be Improved for responsive design.
- [x] #846 The username is now alligned correctly when in responsive mode.
- [x] #848 When responsive, only simple search will be available in the user list.
- [x] #853 Breadcrumbs and the action bar won't collide with other elements in responsive design anymore.
## Changes
- [x] #807 The link to the user's profile is disabled when "View user information" is disabled.
- [x] #821 The 'Submit' label in the user list search has been replaced with 'Search'.
- [x] #826 The "Delete avatar" button will no long be shown when the default avatar is used.
- [x] #828 Styles do no longer have to include the Backstage Accent color pallet.
- [x] #835 On the index, topic titles will be cut short after 43 characters instead of 30.
- [x] #842 When changing settings, the 'Submit' button is replaced with 'Save'.
- [x] #847 The pagination won't be displayed anymore when only 1 page is available.
## Bugfixes
- [x] #815 The avatar field will now always take 100 by 100 pixels when required.
- [x] #825 The "Start typing..." placeholder in text areas can now be translated.
- [x] #831 When adding a user in the Backstage, the check doesn't function correctly on PHP 5.4 and lower.
- [x] #840 We have fixed the "Check for updates" button, which in some occasions would not check for updates.
- [x] #841 The upper Submit button in the profile's personality settings has been fixed.
- [x] #852 An issue with non-latin languages has been solved, preventing them to update correctly.
# Commits
## Bugfixes
- [x] 007b2eaae7472b3604e7981afa03c9353f9e3c4b We've fixed the random tab index order in the users-management Backstage page.
- [x] 29861473e100ece8fc42dccf4ed9ee8c03dbc3d9 Fix a bug with check for passwords in user.php in the Backstage.
## Changes
- [x] 0f2711fd194a73e98dd46e82478e12d5cbb218b1 The page number won't be shown in the page title when less then 1 page is available.
# Thanks

There are some people we would like to thank for their colaboration to the ModernBB 3.4.1 milestone!

@akukaj, [alec](http://modernbb.be/forum/profile.php?id=2717), @bbak, @craigydavi, @oldhobbyist, @quy, @studio384 and @visurox
