### ISSUE TITLE
ModernBB 1.7 "Blythe" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#857]
A small update to the old ModernBB 1.6 branch. This is a one-time thing. Don't get used to it.
# Tickets
## Enhancements
- [x] #856 ModernBB 1.7 now supports new TLDs.
- [x] #872 You will no longer see a redirect screen, giving a better experience.
- [x] #873 The TPL files have been improved with better code.
- [x] #876 When an update is required, the interface is much easier to understand.
- [x] #877 Styles have been updated to be lighter and have an improved UI.
- [x] #878 Images have been optimized.
## Changes
- [x] #875 The quick jump has been removed.
- [x] #879 FluxBB 1.4 or higher is required to update to this version of ModernBB.
## Security
- [x] #874 ModernBB will require passwords with at least 6 characters from now on.
# Commits
## Changes
- [x] eeb91d123959f744b4979f4619be4de51f6a9f6e We updated our slogan!
- [x] c7f4cb7ea29d0a76acfe03e92348295f09bde912 We also updated our logo.
- [x] 3ed223907c8cf461bb7996268b5f35b4387dead4 Internet Explorer 6 is no longer supported.
## Bugfixes
- [x] 825d6491cc694e2bab81a405de304220e785f5de We fixed a major bug for anyone who updates from FluxBB 1.5.x.
