### ISSUE TITLE
Port all fixes from ModernBB 1.6.2

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#86]
It's obvious what needs to be done: fix all issues that are fixed in ModernBB 1.6.2. Since this is a Meta-ticket, we won't allow any comments here.
- [x] #156 Referrer check breaks with UTF-8 URLs 
- [x] #155 Moderators can edit Admin's posts
- [x] #154 Broken PostgreSQL support on 1.5.1+ with o_redirect_delay == 0
- [x] #153 Problem with PHP_EOL constant and email.php
- [x] #152 When no forums, statistics are wrong displayed
- [x] #151 Strict standards error in PostgreSQL adapter
- [x] #150 forum administration
- [x] #149 Caching breaks on concurrent access, possible information disclosure
- [x] #148 When update is unable to add o_base_url, it gives wrong warning
- [x] #147  Escaping admin's mail
- [x] #146 Redirect URL after email dialog not verified

https://github.com/ModernBB/ModernBB/compare/1.6.1...1.6.2
