### ISSUE TITLE
ModernBB 3.4.2 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#860]
ModernBB 3.4 Update 2 is our second update to the ModernBB core for the 3.4 branch. Like Update 1, it will bring small new features and enhandcements.
# Tickets
## Enhancements
- [x] #811 When hovering over a button in the toolbar, it will now show what button it is.
- [x] #851 ModernBB will now allow the usage of new gTLDs.
- [x] #858 The "New User" script for the Backstage has been revamped.
- [x] #864 Multiple improvements and fixes to login and registration interface.
- [x] #868 Improved compatibility with Bootstrap 3.2.
- [x] #871 We've removed the redirect.tpl file, as this is no longer used.
## Bugfixes
- [x] #850 An issue with the markup for the online list has been fixed.
- [x] #854 Lists will no longer get pharagraph tags.
- [x] #880 We've fixed 2 errors when installing ModernBB.
# Commits
## Enhancements
- [x] 5e332c619ab742d47edc6c78c92a5484a6cf386e We've improved the design of the update form slightly.
- [x] cca86c831f54b5e79aca27572e5dacf484f85847 Some old help information has been removed.
## Bugfixes
- [x] a7a87caba1458fd7ae9bf2a10871551d7e5eea66 Fixed a small markup issue in Reports.
