### ISSUE TITLE
ModernBB 3.5.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#924]
ModernBB 3.5 Update 1 is our first update to the ModernBB 3.5 branch. And many will follow.
# Tickets
## Security
- [x] #939 A security issue has been fixed.
## Enhancements
- [x] #923 When a plugin page is open, it no longer has an active state.
- [x] #932 "Users online" will stay up-to-date better.
- [x] #936 Improved support for YouTube videos.
## Bugs
- [x] #920 Issues with the login interface have been fixed.
- [x] #921 When quoting a list, it won't be extra large anymore.
- [x] #922 Admin group permissions won't get altered in the database anymore.
  - [x] #925 The fix for this issue.
- [x] #931 jQuery will no longer fail to load on an SSL Certified server.
- [x] #934 "Last edited by" is displayed when asked for it.
- [x] #935 Allignement issues in search have been fixed.
- [x] #938 Fix issue that prevented the default avatar to be displayed when another avatar directory was selected.
- [x] #940 ModernBB will check for the right location when checking for updates again.
