### ISSUE TITLE
ModernBB 3.5.2 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#944]
The shiplist of our very short-term ModernBB 3.5 Update 2. We had to fix another security issue again.
## Security
- [x] #943 A flaw in redirection has been fixed
## Bugfixes
- [x] #933 The newest topic title on the index will be updated too when editing a title
  - [x] #941 Fix for issue 933
  - [x] #942 Extension for issue 933
