### ISSUE TITLE
ModernBB 3.6 "Blue" Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#972]
ModernBB 3.6 is an update that will improve the overal experience, making small additions, changes and improvements to make the forum software better.
# Tickets
## Features
- [x] #974 The navigation bars now handle touch better on non-small touchscreens (phablets, tablets, desktops).
- [x] #978 You can upgrade from ModernBB 1.x again.
- [x] #981 Luna, Pinkie, Shy, Happy and Magic are back default styles.
## Security
- [x] #977 ModernBB now generates longer passwords.
- [x] #983 Fixes another security issue.
## Backstage
- [x] #975 The Backstage navbar has received an update to break the white look of the Backstage.
- [x] #976 Make the Backstage interface less bright.
- [x] #982 The core version is now shown in the Backstage.
## Design
- [x] #979 The default styles have received a major upgrade to version 4.0.
- [x] #980 Board statistics no longer have a heading.
- [x] #985 The "Change email" interface has been drasticaly improved.
## Enhancements
- [x] #989 We made the "Post" and "Topic" setting in the profile more clear.
## Components
- [x] #973 Bootstrap has been updated from version 3.2.0 to version 3.3.1.
## Bugfixes
- [x] #948 An issue with the URL and IMG tag being used at once has been fixed.
- [x] #952 We removed a pointless if-statement.
- [x] #970 The video hight and weight are now displayed in their own fields instead of each others.
- [x] #986 The avatar file size field no longer shows "pixels".
- [x] #987 A bug that caused the "posts" label to be replaced with "post" on the index has been fixed.
- [x] #990 A bug in validate_redirect() has been fixed.
# Commits
## Backstage
- [x] 65582d5 The Backstage now has less whitespace at the end of panels.
## Design
- [x] 14358ab The "Choose user group" interface has been Improved.
