### ISSUE TITLE
Merge changes from ModernBB 3.6 into Luna

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#992]
Below is a list of tickets that have been fixed in ModernBB 3.6 but yet have to be done in Luna 1.0. This the the Luna 1.0 Preview 1 final ticket, when this is done (which will happen in the lunarelease branch), we're ready to go with Luna 0.1! Other features will be developed for the 2nd Preview (while some may arrive already in updates to the first preview).
# Tickets
## Features
- [x] #974 The navigation bars now handle touch better on non-small touchscreens (phablets, tablets, desktops).
## Security
- [x] #977 Luna now generates longer passwords.
## Design
- [x] #985 The "Change email" interface has been drasticaly improved.
## Enhancements
- [x] #989 We made the "Post" and "Topic" setting in the profile more clear.
## Bugfixes
- [x] #952 We removed a pointless if-statement.
- [x] #986 The avatar file size field no longer shows "pixels".
# Commits
## Backstage
- [x] 65582d5 The Backstage now has less whitespace at the end of panels.
## Design
- [x] 14358ab The "Choose user group" interface has been improved.
