### ISSUE TITLE
ModernBB 3.6.1 Shiplist

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#997]
ModernBB 3.6.1 is our first and only bugfix release for ModernBB 3.6 Blue. After this, I hope ModernBB 3.7 "Cotton Candy" is out there.
## Bugfixes
- [x] #994 Guests will no longer get to see the Bootstrap installation and changing the theme won't brick the board design upon updating.
- [x] #996 The login button in the First Run has been corrected.
- [x] #1002 When the database needs to get updated, it will fail.
